name: CI

on:
  push:
  pull_request_target:
  schedule:
    - cron: "6 20 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5.0"
          - "2.5"
          - "2.6.0"
          - "2.6"
          - "2.7.0"
          - "2.7"
          - "3.0.0"
          - ruby-head
          - jruby-9.2
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
